-- BilX canonical Supabase schema.
-- Run this in Supabase SQL Editor before using the app.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'student' check (role in ('student', 'instructor')),
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."Courses" (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null default 0,
  instructor_id uuid references auth.users(id) on delete set null,
  instructor_name text,
  thumbnail_url text,
  is_published boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  title text not null,
  video_url text not null,
  order_index integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  status text not null default 'active',
  enrolled_at timestamptz not null default now(),
  unique (user_id, course_id)
);

create table if not exists public.video_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  watched boolean not null default false,
  position_seconds numeric not null default 0,
  last_opened_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, video_id)
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  user_name text,
  course_id bigint references public."Courses"(id) on delete cascade,
  course_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public."Courses"
  add column if not exists instructor_name text,
  add column if not exists thumbnail_url text,
  add column if not exists is_published boolean not null default false,
  add column if not exists status text not null default 'draft',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.enrollments
  add column if not exists status text not null default 'active',
  add column if not exists enrolled_at timestamptz not null default now();

grant usage on schema public to anon, authenticated;
grant select on public."Courses" to anon, authenticated;
grant select on public.profiles to anon;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.videos to authenticated;
grant select, insert, update, delete on public.enrollments to authenticated;
grant select, insert, update on public.video_progress to authenticated;
grant select, insert, update on public.requests to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles enable row level security;
alter table public."Courses" enable row level security;
alter table public.videos enable row level security;
alter table public.enrollments enable row level security;
alter table public.video_progress enable row level security;
alter table public.requests enable row level security;

drop policy if exists "profiles_read_own_or_admin" on public.profiles;
drop policy if exists "profiles_read_public_course_instructors" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
drop policy if exists "profiles_admin_update_all" on public.profiles;
drop policy if exists "courses_public_read_approved" on public."Courses";
drop policy if exists "courses_instructor_read_own" on public."Courses";
drop policy if exists "courses_admin_read_all" on public."Courses";
drop policy if exists "courses_instructor_insert_own" on public."Courses";
drop policy if exists "courses_instructor_update_own" on public."Courses";
drop policy if exists "courses_admin_update_all" on public."Courses";
drop policy if exists "videos_read_for_owner_or_enrolled" on public.videos;
drop policy if exists "videos_insert_for_course_owner" on public.videos;
drop policy if exists "videos_update_for_course_owner" on public.videos;
drop policy if exists "videos_delete_for_course_owner" on public.videos;
drop policy if exists "enrollments_admin_all" on public.enrollments;
drop policy if exists "enrollments_student_read_own" on public.enrollments;
drop policy if exists "progress_student_all_own" on public.video_progress;
drop policy if exists "requests_insert_own" on public.requests;
drop policy if exists "requests_admin_read_all" on public.requests;
drop policy if exists "requests_admin_update_all" on public.requests;

create policy "profiles_read_own_or_admin"
  on public.profiles for select
  using (user_id = auth.uid() or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "profiles_read_public_course_instructors"
  on public.profiles for select
  using (
    role = 'instructor'
    and exists (
      select 1
      from public."Courses" c
      where c.instructor_id = profiles.user_id
        and c.is_published = true
    )
  );

-- New profiles may only be created for oneself and only as a student.
-- Promotion to instructor happens exclusively through the admin review RPC
-- (see teacher_applications.sql), never by self-insert.
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (user_id = auth.uid() and role = 'student');

-- Role changes (and any profile mutation) are admin-only so a user cannot
-- escalate their own role to 'instructor' by updating their profile row.
create policy "profiles_admin_update_all"
  on public.profiles for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "courses_public_read_approved"
  on public."Courses" for select
  using (is_published = true and status = 'approved');

create policy "courses_instructor_read_own"
  on public."Courses" for select
  using (instructor_id = auth.uid());

create policy "courses_admin_read_all"
  on public."Courses" for select
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "courses_instructor_insert_own"
  on public."Courses" for insert
  with check (instructor_id = auth.uid());

create policy "courses_instructor_update_own"
  on public."Courses" for update
  using (instructor_id = auth.uid())
  with check (instructor_id = auth.uid());

create policy "courses_admin_update_all"
  on public."Courses" for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "videos_read_for_owner_or_enrolled"
  on public.videos for select
  using (
    exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
    or exists (
      select 1 from public.enrollments e
      where e.course_id::text = videos.course_id::text
        and coalesce(e.status, 'active') = 'active'
        and (e.user_id::text = auth.uid()::text or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', '')))
    )
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "videos_insert_for_course_owner"
  on public.videos for insert
  with check (exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid()));

create policy "videos_update_for_course_owner"
  on public.videos for update
  using (exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid()))
  with check (exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid()));

create policy "videos_delete_for_course_owner"
  on public.videos for delete
  using (exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid()));

create policy "enrollments_admin_all"
  on public.enrollments for all
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "enrollments_student_read_own"
  on public.enrollments for select
  using (user_id::text = auth.uid()::text or lower(user_id::text) = lower(coalesce(auth.jwt() ->> 'email', '')));

create policy "progress_student_all_own"
  on public.video_progress for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "requests_insert_own"
  on public.requests for insert
  with check (user_id = auth.uid());

create policy "requests_admin_read_all"
  on public.requests for select
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "requests_admin_update_all"
  on public.requests for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');
