-- Section quizzes for BilX course content.
-- Safe to run more than once.

create table if not exists public.course_quizzes (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  section_id bigint not null references public.course_sections(id) on delete cascade,
  title text not null,
  questions jsonb not null default '[]'::jsonb,
  is_free boolean not null default false,
  order_index integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.course_quizzes
  add column if not exists is_free boolean not null default false;

create index if not exists course_quizzes_course_idx on public.course_quizzes(course_id);
create index if not exists course_quizzes_section_idx on public.course_quizzes(section_id);

grant select on public.course_quizzes to authenticated;
grant select on public.course_quizzes to anon;
grant insert, update, delete on public.course_quizzes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.course_quizzes enable row level security;

drop policy if exists "course_quizzes_read_allowed" on public.course_quizzes;
drop policy if exists "course_quizzes_insert_owner" on public.course_quizzes;
drop policy if exists "course_quizzes_update_owner" on public.course_quizzes;
drop policy if exists "course_quizzes_delete_owner" on public.course_quizzes;

create policy "course_quizzes_read_allowed"
  on public.course_quizzes for select
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_quizzes.course_id
        and (
          c.instructor_id = auth.uid()
          or public.is_admin()
          or public.has_course_access(c.id)
          or (
            course_quizzes.is_free = true
            and c.is_published = true
          )
        )
    )
  );

create policy "course_quizzes_insert_owner"
  on public.course_quizzes for insert
  with check (
    exists (
      select 1 from public."Courses" c
      where c.id = course_quizzes.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
    and exists (
      select 1 from public.course_sections s
      where s.id = course_quizzes.section_id
        and s.course_id = course_quizzes.course_id
    )
  );

create policy "course_quizzes_update_owner"
  on public.course_quizzes for update
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_quizzes.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  )
  with check (
    exists (
      select 1 from public."Courses" c
      where c.id = course_quizzes.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
    and exists (
      select 1 from public.course_sections s
      where s.id = course_quizzes.section_id
        and s.course_id = course_quizzes.course_id
    )
  );

create policy "course_quizzes_delete_owner"
  on public.course_quizzes for delete
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_quizzes.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  );

-- Public, answer-free quiz outline for published courses. This lets students
-- see tests in the curriculum before buying without exposing quiz answers.
drop view if exists public.course_quiz_previews;
create view public.course_quiz_previews
with (security_invoker = false)
as
  select
    q.id,
    q.course_id,
    q.section_id,
    q.title,
    jsonb_array_length(coalesce(q.questions, '[]'::jsonb)) as question_count,
    q.is_free,
    q.order_index
  from public.course_quizzes q
  join public."Courses" c on c.id = q.course_id
  where c.is_published = true;

grant select on public.course_quiz_previews to anon, authenticated;

update public.course_quizzes q
set is_free = true
from public."Courses" c
where c.id = q.course_id
  and c.id = 17
  and c.is_published = true
  and q.title ~* '(^|[[:space:]])test[[:space:]]*4([^0-9]|$)';

notify pgrst, 'reload schema';
