-- Course sections and completion certificates.
-- Idempotent: safe to run more than once.

create table if not exists public.course_sections (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  title text not null,
  order_index integer not null default 1,
  created_at timestamptz not null default now(),
  unique (course_id, order_index)
);

alter table public.videos
  add column if not exists section_id bigint references public.course_sections(id) on delete set null;

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  verification_code uuid not null default gen_random_uuid() unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  student_name text not null,
  course_title text not null,
  instructor_name text,
  issued_at timestamptz not null default now(),
  unique (user_id, course_id)
);

-- Give every existing course a first section, then preserve every existing video
-- by placing it into that section.
insert into public.course_sections (course_id, title, order_index)
select c.id, 'Section 1', 1
from public."Courses" c
where not exists (
  select 1 from public.course_sections s where s.course_id = c.id
);

update public.videos v
set section_id = s.id
from public.course_sections s
where v.section_id is null
  and s.course_id = v.course_id
  and s.order_index = 1;

grant select on public.course_sections to anon, authenticated;
grant insert, update, delete on public.course_sections to authenticated;
grant select on public.certificates to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.course_sections enable row level security;
alter table public.certificates enable row level security;

drop policy if exists "course_sections_read_visible" on public.course_sections;
drop policy if exists "course_sections_insert_owner" on public.course_sections;
drop policy if exists "course_sections_update_owner" on public.course_sections;
drop policy if exists "course_sections_delete_owner" on public.course_sections;

create policy "course_sections_read_visible"
  on public.course_sections for select
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_sections.course_id
        and (
          c.is_published = true
          or c.instructor_id = auth.uid()
          or public.is_admin()
          or public.has_course_access(c.id)
        )
    )
  );

create policy "course_sections_insert_owner"
  on public.course_sections for insert
  with check (
    exists (
      select 1 from public."Courses" c
      where c.id = course_sections.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  );

create policy "course_sections_update_owner"
  on public.course_sections for update
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_sections.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  )
  with check (
    exists (
      select 1 from public."Courses" c
      where c.id = course_sections.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  );

create policy "course_sections_delete_owner"
  on public.course_sections for delete
  using (
    exists (
      select 1 from public."Courses" c
      where c.id = course_sections.course_id
        and c.instructor_id = auth.uid()
        and coalesce(c.status, 'draft') <> 'approved'
    )
  );

drop policy if exists "certificates_read_own_or_admin" on public.certificates;
create policy "certificates_read_own_or_admin"
  on public.certificates for select
  using (user_id = auth.uid() or public.is_admin());

create or replace function public.issue_course_certificate(p_course_id bigint)
returns public.certificates
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user auth.users%rowtype;
  target_course public."Courses"%rowtype;
  total_lessons integer;
  completed_lessons integer;
  result public.certificates%rowtype;
begin
  select * into target_user from auth.users where id = auth.uid();
  if target_user.id is null then
    raise exception 'Authentication required';
  end if;

  select * into target_course from public."Courses" where id = p_course_id;
  if target_course.id is null then
    raise exception 'Course not found';
  end if;

  if not public.has_course_access(p_course_id) then
    raise exception 'Active course access required';
  end if;

  select count(*) into total_lessons
  from public.videos
  where course_id = p_course_id;

  select count(*) into completed_lessons
  from public.video_progress vp
  join public.videos v on v.id = vp.video_id
  where vp.user_id = auth.uid()
    and vp.watched = true
    and v.course_id = p_course_id;

  if total_lessons = 0 or completed_lessons < total_lessons then
    raise exception 'Complete every lesson before requesting a certificate';
  end if;

  insert into public.certificates (
    user_id,
    course_id,
    student_name,
    course_title,
    instructor_name
  )
  values (
    auth.uid(),
    p_course_id,
    coalesce(
      (select p.full_name from public.profiles p where p.user_id = auth.uid()),
      target_user.raw_user_meta_data ->> 'full_name',
      target_user.email
    ),
    target_course.title,
    target_course.instructor_name
  )
  on conflict (user_id, course_id) do update
    set student_name = excluded.student_name,
        course_title = excluded.course_title,
        instructor_name = excluded.instructor_name
  returning * into result;

  return result;
end;
$$;

revoke all on function public.issue_course_certificate(bigint) from public;
grant execute on function public.issue_course_certificate(bigint) to authenticated;

create or replace function public.verify_certificate(p_code uuid)
returns table (
  verification_code uuid,
  student_name text,
  course_title text,
  instructor_name text,
  issued_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select c.verification_code, c.student_name, c.course_title, c.instructor_name, c.issued_at
  from public.certificates c
  where c.verification_code = p_code;
$$;

grant execute on function public.verify_certificate(uuid) to anon, authenticated;

-- Include section metadata in the public curriculum without exposing video URLs.
drop view if exists public.lesson_previews;
create view public.lesson_previews
with (security_invoker = false)
as
  select v.id, v.course_id, v.section_id, v.title, v.duration, v.order_index, v.is_free
  from public.videos v
  join public."Courses" c on c.id = v.course_id
  where c.is_published = true;

grant select on public.lesson_previews to anon, authenticated;

notify pgrst, 'reload schema';
