-- Align enrollments column types with the canonical schema and the app's
-- identity model, then restore all affected RLS policies.
--
-- The live table had user_id as uuid and course_id as text, which is the
-- reverse of bilx_schema.sql (user_id text, course_id bigint). The app grants
-- access by email (AdminDashboard.giveAccess) and reads enrollments by both the
-- user's UUID and email (CoursePage / StudentProfile / Inbox), which requires
-- user_id to be text. course_id is numeric everywhere and should match
-- Courses.id (bigint).
--
-- Postgres will not alter a column type while a policy depends on it, and
-- policies on videos / video_comments / course_ratings reference enrollments
-- columns in subqueries. So this script drops every policy on those four tables
-- (including any created manually in the dashboard), changes the types, adds the
-- missing unique constraint, then recreates the canonical policies.
--
-- This is self-contained: one run leaves the database fully working.

-- 0. Instructor-role check as a SECURITY DEFINER function (avoids the
--    Courses <-> profiles policy recursion). Idempotent; safe if it already
--    exists from fix_rls_recursion.sql / teacher_applications.sql.
create or replace function public.is_approved_instructor()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'instructor'
  );
$$;

grant execute on function public.is_approved_instructor() to authenticated, anon;

-- 1. Drop every policy on tables that reference enrollments columns.
do $$
declare
  r record;
begin
  for r in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('enrollments', 'videos', 'video_comments', 'course_ratings')
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- 2. Drop any foreign-key constraint that includes enrollments.user_id.
do $$
declare
  r record;
begin
  for r in
    select c.conname
    from pg_constraint c
    where c.conrelid = 'public.enrollments'::regclass
      and c.contype = 'f'
      and 'user_id' = any (
        select a.attname
        from pg_attribute a
        where a.attrelid = c.conrelid
          and a.attnum = any (c.conkey)
      )
  loop
    execute 'alter table public.enrollments drop constraint ' || quote_ident(r.conname);
  end loop;
end $$;

-- 3. Change column types. Drop column defaults first: a text default on
--    course_id (or user_id) cannot be auto-cast to the new type.
alter table public.enrollments
  alter column user_id drop default,
  alter column course_id drop default;

alter table public.enrollments
  alter column user_id type text using user_id::text;
alter table public.enrollments
  alter column course_id type bigint using course_id::bigint;

-- 4. Add any canonical columns the live table is missing. Older versions of this
--    table had no id / status / enrolled_at. The app uses enrollments.id
--    (AdminDashboard.removeAccess), so it must exist.
alter table public.enrollments
  add column if not exists id bigint generated by default as identity,
  add column if not exists status text not null default 'active',
  add column if not exists enrolled_at timestamptz not null default now();

-- 4b. Ensure a primary key exists (use id if the table has none).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.enrollments'::regclass and contype = 'p'
  ) then
    alter table public.enrollments add primary key (id);
  end if;
end $$;

-- 5. Remove duplicate (user_id, course_id) rows, keeping one per pair. Uses ctid
--    (present on every row) so it works regardless of which columns exist.
delete from public.enrollments a
using public.enrollments b
where a.ctid < b.ctid
  and a.user_id = b.user_id
  and a.course_id = b.course_id;

-- 6. Add the unique(user_id, course_id) constraint the app's upsert relies on.
do $$
begin
  alter table public.enrollments
    add constraint enrollments_user_id_course_id_key unique (user_id, course_id);
exception
  when duplicate_object then null;
  when duplicate_table then null;
end $$;

-- 6. Recreate the canonical policies that were dropped in step 1.

-- enrollments (bilx_schema.sql)
create policy "enrollments_admin_all"
  on public.enrollments for all
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "enrollments_student_read_own"
  on public.enrollments for select
  using (user_id::text = auth.uid()::text or lower(user_id::text) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- videos: read (bilx_schema.sql), write (teacher_applications.sql, role-checked)
create policy "videos_read_for_owner_or_enrolled"
  on public.videos for select
  using (
    exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
    or exists (
      select 1 from public.enrollments e
      where e.course_id::text = videos.course_id::text
        and coalesce(e.status, 'active') = 'active'
        and (e.user_id::text = auth.uid()::text or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', '')))
    )
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "videos_insert_for_course_owner"
  on public.videos for insert
  with check (
    public.is_approved_instructor()
    and exists (
      select 1
      from public."Courses" c
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

create policy "videos_update_for_course_owner"
  on public.videos for update
  using (
    public.is_approved_instructor()
    and exists (
      select 1
      from public."Courses" c
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  )
  with check (
    public.is_approved_instructor()
    and exists (
      select 1
      from public."Courses" c
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

create policy "videos_delete_for_course_owner"
  on public.videos for delete
  using (
    public.is_approved_instructor()
    and exists (
      select 1
      from public."Courses" c
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

-- video_comments + course_ratings (phase2_schema.sql). Guarded so this file is
-- safe even if phase2_schema.sql has not been run yet (the tables may not exist).
do $do$
begin
  if to_regclass('public.video_comments') is not null then
    execute $pol$
      create policy "video_comments_read_enrolled_or_owner"
        on public.video_comments for select
        using (
          exists (
            select 1
            from public.videos v
            join public."Courses" c on c.id = v.course_id
            where v.id = video_comments.video_id
              and (
                c.instructor_id::text = auth.uid()::text
                or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
              )
          )
          or exists (
            select 1
            from public.videos v
            join public.enrollments e on e.course_id::text = v.course_id::text
            where v.id = video_comments.video_id
              and coalesce(e.status, 'active') = 'active'
              and (
                e.user_id::text = auth.uid()::text
                or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
              )
          )
        )
    $pol$;

    execute $pol$
      create policy "video_comments_insert_enrolled"
        on public.video_comments for insert
        with check (
          user_id::text = auth.uid()::text
          and exists (
            select 1
            from public.videos v
            join public.enrollments e on e.course_id::text = v.course_id::text
            where v.id = video_comments.video_id
              and coalesce(e.status, 'active') = 'active'
              and (
                e.user_id::text = auth.uid()::text
                or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
              )
          )
        )
    $pol$;
  end if;

  if to_regclass('public.course_ratings') is not null then
    execute $pol$
      create policy "course_ratings_read_any"
        on public.course_ratings for select
        using (true)
    $pol$;

    execute $pol$
      create policy "course_ratings_insert_enrolled"
        on public.course_ratings for insert
        with check (
          user_id::text = auth.uid()::text
          and exists (
            select 1
            from public.enrollments e
            where e.course_id::text = course_ratings.course_id::text
              and coalesce(e.status, 'active') = 'active'
              and (
                e.user_id::text = auth.uid()::text
                or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
              )
          )
        )
    $pol$;

    execute $pol$
      create policy "course_ratings_update_own"
        on public.course_ratings for update
        using (user_id::text = auth.uid()::text)
        with check (user_id::text = auth.uid()::text)
    $pol$;
  end if;
end
$do$;

notify pgrst, 'reload schema';
