-- Phase 2 core schema: notifications, inbox, comments, ratings.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.inbox_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_email text not null,
  recipient_id uuid references auth.users(id) on delete set null,
  recipient_email text,
  course_id bigint references public."Courses"(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.course_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  review text,
  created_at timestamptz not null default now(),
  unique (user_id, course_id)
);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.notifications to authenticated;
grant select, insert, update on public.inbox_messages to authenticated;
grant select, insert on public.video_comments to authenticated;
grant select, insert, update on public.course_ratings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.notifications enable row level security;
alter table public.inbox_messages enable row level security;
alter table public.video_comments enable row level security;
alter table public.course_ratings enable row level security;

drop policy if exists "notifications_read_own_or_admin" on public.notifications;
drop policy if exists "notifications_insert_own" on public.notifications;
drop policy if exists "notifications_update_own_or_admin" on public.notifications;

create policy "notifications_read_own_or_admin"
  on public.notifications for select
  using (
    user_id::text = auth.uid()::text
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "notifications_insert_own"
  on public.notifications for insert
  with check (user_id::text = auth.uid()::text);

create policy "notifications_update_own_or_admin"
  on public.notifications for update
  using (
    user_id::text = auth.uid()::text
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  )
  with check (
    user_id::text = auth.uid()::text
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

drop policy if exists "inbox_read_participants_or_admin" on public.inbox_messages;
drop policy if exists "inbox_insert_sender" on public.inbox_messages;
drop policy if exists "inbox_update_participants" on public.inbox_messages;

create policy "inbox_read_participants_or_admin"
  on public.inbox_messages for select
  using (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "inbox_insert_sender"
  on public.inbox_messages for insert
  with check (
    sender_id::text = auth.uid()::text
    and lower(sender_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

create policy "inbox_update_participants"
  on public.inbox_messages for update
  using (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  )
  with check (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

drop policy if exists "video_comments_read_enrolled_or_owner" on public.video_comments;
drop policy if exists "video_comments_insert_enrolled" on public.video_comments;

create policy "video_comments_read_enrolled_or_owner"
  on public.video_comments for select
  using (
    exists (
      select 1
      from public.videos v
      join public."Courses" c on c.id = v.course_id
      where v.id = video_comments.video_id
        and (
          c.instructor_id::text = auth.uid()::text
          or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
        )
    )
    or exists (
      select 1
      from public.videos v
      join public.enrollments e on e.course_id::text = v.course_id::text
      where v.id = video_comments.video_id
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

create policy "video_comments_insert_enrolled"
  on public.video_comments for insert
  with check (
    user_id::text = auth.uid()::text
    and exists (
      select 1
      from public.videos v
      join public.enrollments e on e.course_id::text = v.course_id::text
      where v.id = video_comments.video_id
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

drop policy if exists "course_ratings_read_any" on public.course_ratings;
drop policy if exists "course_ratings_insert_enrolled" on public.course_ratings;
drop policy if exists "course_ratings_update_own" on public.course_ratings;

create policy "course_ratings_read_any"
  on public.course_ratings for select
  using (true);

create policy "course_ratings_insert_enrolled"
  on public.course_ratings for insert
  with check (
    user_id::text = auth.uid()::text
    and exists (
      select 1
      from public.enrollments e
      where e.course_id::text = course_ratings.course_id::text
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

create policy "course_ratings_update_own"
  on public.course_ratings for update
  using (user_id::text = auth.uid()::text)
  with check (user_id::text = auth.uid()::text);

notify pgrst, 'reload schema';
