create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  quiz_id bigint not null references public.course_quizzes(id) on delete cascade,
  answers jsonb not null default '[]'::jsonb,
  correct_count integer not null default 0,
  total_count integer not null default 0,
  completed_at timestamptz not null default now(),
  unique (user_id, quiz_id)
);

create index if not exists quiz_attempts_user_course_idx
  on public.quiz_attempts (user_id, course_id);

alter table public.quiz_attempts enable row level security;
grant select, insert, update, delete on public.quiz_attempts to authenticated;
grant usage, select on sequence public.quiz_attempts_id_seq to authenticated;

drop policy if exists "quiz_attempts_student_own" on public.quiz_attempts;
create policy "quiz_attempts_student_own"
  on public.quiz_attempts for all
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.enrollments e
      where e.course_id = quiz_attempts.course_id
        and e.status = 'active'
        and e.user_id = auth.uid()::text
    )
  );
