-- ============================================================================
-- Bil-X consolidated reconcile script.
--
-- Idempotent. Brings an existing (possibly older) database fully up to the
-- canonical schema in a single run: tables, missing columns, column types,
-- constraints, grants, RLS policies, functions and triggers. Safe to run
-- repeatedly. Supersedes running bilx_schema.sql + teacher_applications.sql +
-- phase2_schema.sql + the various fix_* / phase1_* patches individually.
--
-- The only thing it cannot auto-resolve is non-numeric data in a column being
-- converted to bigint (enrollments.course_id). If that errors, clean the data
-- and re-run.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tables (no-op if they already exist; older tables are patched in step 2+).
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'student' check (role in ('student', 'instructor')),
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."Courses" (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null default 0,
  instructor_id uuid references auth.users(id) on delete set null,
  instructor_name text,
  thumbnail_url text,
  is_published boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  title text not null,
  -- Bunny lessons reference a video by GUID and have no video_url; legacy
  -- YouTube/Storage lessons still carry a video_url. So video_url is nullable.
  video_url text,
  bunny_video_id text,
  video_source text not null default 'bunny',
  order_index integer not null default 1,
  is_free boolean not null default false,
  duration text,
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  status text not null default 'active',
  enrolled_at timestamptz not null default now(),
  unique (user_id, course_id)
);

create table if not exists public.video_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  watched boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, video_id)
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  user_name text,
  course_id bigint references public."Courses"(id) on delete cascade,
  course_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  surname text not null,
  phone text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.inbox_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_email text not null,
  recipient_id uuid references auth.users(id) on delete set null,
  recipient_email text,
  course_id bigint references public."Courses"(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.course_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public."Courses"(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  review text,
  created_at timestamptz not null default now(),
  unique (user_id, course_id)
);

-- ---------------------------------------------------------------------------
-- 2. Add columns missing from older tables.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public."Courses"
  add column if not exists instructor_name text,
  add column if not exists thumbnail_url text,
  add column if not exists is_published boolean not null default false,
  add column if not exists status text not null default 'draft',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.videos
  add column if not exists order_index integer not null default 1,
  add column if not exists is_free boolean not null default false,
  add column if not exists duration text,
  add column if not exists created_at timestamptz not null default now(),
  -- Bunny Stream hosting (see supabase/add_bunny_video.sql for details).
  add column if not exists bunny_video_id text,
  add column if not exists video_source text not null default 'bunny';

-- Lessons hosted on Bunny have no public URL.
alter table public.videos
  alter column video_url drop not null;

-- Tag pre-existing rows (all of which carry a video_url) as legacy so the
-- player keeps serving them through the old YouTube/file path.
update public.videos
  set video_source = 'legacy'
  where bunny_video_id is null
    and video_url is not null
    and video_source = 'bunny';

alter table public.teacher_applications
  add column if not exists status text not null default 'pending',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists reviewed_at timestamptz;

create unique index if not exists teacher_applications_one_pending_per_user
  on public.teacher_applications (user_id)
  where status = 'pending';

-- ---------------------------------------------------------------------------
-- 3. Drop every policy on managed tables. Required so enrollments columns can
--    change type, and so the canonical policies in step 8 are the only ones
--    left (removes any stray/manual dashboard policies).
-- ---------------------------------------------------------------------------
do $$
declare
  r record;
begin
  for r in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles', 'Courses', 'videos', 'enrollments', 'video_progress',
        'requests', 'teacher_applications', 'notifications', 'inbox_messages',
        'video_comments', 'course_ratings'
      )
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Reconcile enrollments structure & types (user_id -> text, course_id ->
--    bigint, add id/status/enrolled_at, primary key, unique constraint).
-- ---------------------------------------------------------------------------
-- Drop any FK that includes enrollments.user_id, so its type can change.
do $$
declare
  r record;
begin
  for r in
    select c.conname
    from pg_constraint c
    where c.conrelid = 'public.enrollments'::regclass
      and c.contype = 'f'
      and 'user_id' = any (
        select a.attname from pg_attribute a
        where a.attrelid = c.conrelid and a.attnum = any (c.conkey)
      )
  loop
    execute 'alter table public.enrollments drop constraint ' || quote_ident(r.conname);
  end loop;
end $$;

-- Defaults must be dropped before a type change that cannot auto-cast.
alter table public.enrollments
  alter column user_id drop default,
  alter column course_id drop default;

alter table public.enrollments
  alter column user_id type text using user_id::text;
alter table public.enrollments
  alter column course_id type bigint using course_id::bigint;

alter table public.enrollments
  add column if not exists id bigint generated by default as identity,
  add column if not exists status text not null default 'active',
  add column if not exists enrolled_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.enrollments'::regclass and contype = 'p'
  ) then
    alter table public.enrollments add primary key (id);
  end if;
end $$;

delete from public.enrollments a
using public.enrollments b
where a.ctid < b.ctid
  and a.user_id = b.user_id
  and a.course_id = b.course_id;

do $$
begin
  alter table public.enrollments
    add constraint enrollments_user_id_course_id_key unique (user_id, course_id);
exception
  when duplicate_object then null;
  when duplicate_table then null;
end $$;

-- ---------------------------------------------------------------------------
-- 5. Grants.
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant select on public."Courses" to anon, authenticated;
grant select on public.profiles to anon;
grant select, insert, update on public.profiles to authenticated;
grant select on public.videos to anon;
grant select, insert, update, delete on public.videos to authenticated;
grant select, insert, update, delete on public.enrollments to authenticated;
grant select, insert, update on public.video_progress to authenticated;
grant select, insert, update on public.requests to authenticated;
grant select, insert, update on public.teacher_applications to authenticated;
grant select, insert, update on public.notifications to authenticated;
grant select, insert, update on public.inbox_messages to authenticated;
grant select, insert on public.video_comments to authenticated;
grant select, insert, update on public.course_ratings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Enable RLS.
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public."Courses" enable row level security;
alter table public.videos enable row level security;
alter table public.enrollments enable row level security;
alter table public.video_progress enable row level security;
alter table public.requests enable row level security;
alter table public.teacher_applications enable row level security;
alter table public.notifications enable row level security;
alter table public.inbox_messages enable row level security;
alter table public.video_comments enable row level security;
alter table public.course_ratings enable row level security;

-- ---------------------------------------------------------------------------
-- 7. Functions & trigger.
-- ---------------------------------------------------------------------------

-- Single source of truth for "is the current user the admin". All policies and
-- admin RPCs call this, so changing the admin means editing one place here (plus
-- ADMIN_EMAIL in src/profileApi.js on the app side).
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com';
$$;
grant execute on function public.is_admin() to authenticated, anon;

-- Instructor-role check that bypasses RLS (avoids Courses <-> profiles recursion).
create or replace function public.is_approved_instructor()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'instructor'
  );
$$;
grant execute on function public.is_approved_instructor() to authenticated, anon;

-- Active-enrollment check that bypasses RLS/grants. Used inside the videos read
-- policy so a logged-out (anon) viewer — who has no grant on enrollments — can
-- still be evaluated against the policy without a "permission denied" error.
create or replace function public.has_course_access(p_course_id bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.enrollments e
    where e.course_id::text = p_course_id::text
      and coalesce(e.status, 'active') = 'active'
      and (
        e.user_id::text = auth.uid()::text
        or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  );
$$;
grant execute on function public.has_course_access(bigint) to authenticated, anon;

-- Admin-only review of teacher applications (atomic status + role update).
create or replace function public.admin_review_teacher_application(application_id bigint, decision text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user uuid;
  target_full_name text;
begin
  if not public.is_admin() then
    raise exception 'Only admin can review teacher applications';
  end if;

  if decision not in ('approved', 'rejected') then
    raise exception 'Decision must be approved or rejected';
  end if;

  select user_id, trim(name || ' ' || surname) into target_user, target_full_name
  from public.teacher_applications
  where id = application_id and status = 'pending';

  if target_user is null then
    raise exception 'Pending application not found';
  end if;

  update public.teacher_applications
  set status = decision, reviewed_at = now()
  where id = application_id;

  if decision = 'approved' then
    insert into public.profiles (user_id, full_name, role)
    values (target_user, target_full_name, 'instructor')
    on conflict (user_id) do update
      set role = 'instructor', full_name = excluded.full_name;
  end if;
end;
$$;
grant execute on function public.admin_review_teacher_application(bigint, text) to authenticated;

-- Create an in-app notification for another user (bypasses notifications_insert_own).
create or replace function public.create_notification(
  p_user_id uuid,
  p_title text,
  p_body text default null,
  p_link text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Must be authenticated to send notifications';
  end if;
  if p_user_id is null then
    return;
  end if;
  insert into public.notifications (user_id, title, body, link)
  values (p_user_id, p_title, p_body, p_link);
end;
$$;
grant execute on function public.create_notification(uuid, text, text, text) to authenticated;

-- Notify the admin (used when a student submits a teacher application). Resolves
-- the admin's user_id from auth.users so the caller does not need to know it.
create or replace function public.notify_admin(
  p_title text,
  p_body text default null,
  p_link text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Must be authenticated';
  end if;

  select id into admin_id
  from auth.users
  where lower(email) = 'qafarzadep@gmail.com'
  limit 1;

  if admin_id is null then
    return;
  end if;

  insert into public.notifications (user_id, title, body, link)
  values (admin_id, p_title, p_body, p_link);
end;
$$;
grant execute on function public.notify_admin(text, text, text) to authenticated;

-- Admin-only user directory with real emails + signup dates from auth.users.
-- Lets the admin panel show emails without exposing them through the public
-- profiles table. Also reports whether each user is currently banned.
drop function if exists public.admin_list_users();
create or replace function public.admin_list_users()
returns table (
  user_id uuid,
  email text,
  full_name text,
  role text,
  created_at timestamptz,
  banned boolean,
  last_active timestamptz,
  device_info text
)
language sql
security definer
set search_path = public
stable
as $$
  select u.id,
         u.email::text,
         coalesce(p.full_name, u.raw_user_meta_data ->> 'full_name', u.email)::text,
         coalesce(p.role, 'student')::text,
         u.created_at,
         (u.banned_until is not null and u.banned_until > now()) as banned,
         s.last_active,
         s.device_info
  from auth.users u
  left join public.profiles p on p.user_id = u.id
  left join public.user_sessions s on s.user_id = u.id
  where public.is_admin()
  order by u.created_at desc;
$$;
grant execute on function public.admin_list_users() to authenticated;

-- Admin-only: ban / unban a user (GoTrue blocks login while banned_until is in
-- the future). The admin account cannot ban itself.
create or replace function public.admin_set_user_banned(p_user_id uuid, p_banned boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_email text;
begin
  if not public.is_admin() then
    raise exception 'Only admin can ban users';
  end if;
  if p_user_id is null then
    return;
  end if;

  select email into target_email from auth.users where id = p_user_id;
  if lower(coalesce(target_email, '')) = 'qafarzadep@gmail.com' then
    raise exception 'Cannot ban the admin account';
  end if;

  update auth.users
  set banned_until = case when p_banned then 'infinity'::timestamptz else null end
  where id = p_user_id;
end;
$$;
grant execute on function public.admin_set_user_banned(uuid, boolean) to authenticated;

-- Admin-only: permanently delete a user. Most related rows cascade via FK; the
-- email-keyed enrollments do not, so they are removed explicitly. The admin
-- account cannot delete itself.
create or replace function public.admin_delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_email text;
begin
  if not public.is_admin() then
    raise exception 'Only admin can delete users';
  end if;
  if p_user_id is null then
    return;
  end if;

  select email into target_email from auth.users where id = p_user_id;
  if lower(coalesce(target_email, '')) = 'qafarzadep@gmail.com' then
    raise exception 'Cannot delete the admin account';
  end if;

  delete from public.enrollments
  where user_id = p_user_id::text
     or lower(user_id) = lower(coalesce(target_email, ''));

  delete from auth.users where id = p_user_id;
end;
$$;
grant execute on function public.admin_delete_user(uuid) to authenticated;

-- New auth users always get a student profile (role from metadata is ignored).
create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    'student'
  )
  on conflict (user_id) do update
    set full_name = coalesce(excluded.full_name, public.profiles.full_name);
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
  after insert on auth.users
  for each row execute function public.create_profile_for_new_user();

-- ---------------------------------------------------------------------------
-- 8. Policies (canonical, recursion-free, type-cast-safe).
-- ---------------------------------------------------------------------------

-- profiles
create policy "profiles_read_own_or_admin"
  on public.profiles for select
  using (user_id = auth.uid() or public.is_admin());

create policy "profiles_read_public_course_instructors"
  on public.profiles for select
  using (
    role = 'instructor'
    and exists (select 1 from public."Courses" c where c.instructor_id = profiles.user_id and c.is_published = true)
  );

create policy "profiles_insert_own"
  on public.profiles for insert
  with check (user_id = auth.uid() and role = 'student');

create policy "profiles_admin_update_all"
  on public.profiles for update
  using (public.is_admin())
  with check (public.is_admin());

-- Courses
create policy "courses_public_read_approved"
  on public."Courses" for select
  using (is_published = true);

create policy "courses_instructor_read_own"
  on public."Courses" for select
  using (instructor_id = auth.uid() and public.is_approved_instructor());

create policy "courses_admin_read_all"
  on public."Courses" for select
  using (public.is_admin());

create policy "courses_instructor_insert_own"
  on public."Courses" for insert
  with check (instructor_id = auth.uid() and public.is_approved_instructor());

create policy "courses_instructor_update_own"
  on public."Courses" for update
  using (instructor_id = auth.uid() and public.is_approved_instructor())
  with check (instructor_id = auth.uid() and public.is_approved_instructor());

create policy "courses_admin_update_all"
  on public."Courses" for update
  using (public.is_admin())
  with check (public.is_admin());

-- videos
create policy "videos_read_for_owner_or_enrolled"
  on public.videos for select
  using (
    -- Only lessons explicitly marked is_free by the instructor are public.
    -- The dedicated course trailer lives separately in course_trailers.
    (
      videos.is_free = true
      and exists (select 1 from public."Courses" c where c.id = videos.course_id and c.is_published = true)
    )
    or exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
    or public.has_course_access(videos.course_id)
    or public.is_admin()
  );

create policy "videos_insert_for_course_owner"
  on public.videos for insert
  with check (
    public.is_approved_instructor()
    and exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
  );

create policy "videos_update_for_course_owner"
  on public.videos for update
  using (
    public.is_approved_instructor()
    and exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
  )
  with check (
    public.is_approved_instructor()
    and exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
  );

create policy "videos_delete_for_course_owner"
  on public.videos for delete
  using (
    public.is_approved_instructor()
    and exists (select 1 from public."Courses" c where c.id = videos.course_id and c.instructor_id = auth.uid())
  );

-- enrollments
create policy "enrollments_admin_all"
  on public.enrollments for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "enrollments_student_read_own"
  on public.enrollments for select
  using (user_id::text = auth.uid()::text or lower(user_id::text) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- video_progress
create policy "progress_student_all_own"
  on public.video_progress for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- requests
create policy "requests_insert_own"
  on public.requests for insert
  with check (user_id = auth.uid());

create policy "requests_admin_read_all"
  on public.requests for select
  using (public.is_admin());

create policy "requests_admin_update_all"
  on public.requests for update
  using (public.is_admin())
  with check (public.is_admin());

-- teacher_applications
create policy "teacher_applications_insert_own_pending"
  on public.teacher_applications for insert
  with check (
    user_id = auth.uid()
    and email = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status = 'pending'
  );

create policy "teacher_applications_read_own_or_admin"
  on public.teacher_applications for select
  using (user_id = auth.uid() or public.is_admin());

create policy "teacher_applications_admin_update"
  on public.teacher_applications for update
  using (public.is_admin())
  with check (public.is_admin());

-- notifications
create policy "notifications_read_own_or_admin"
  on public.notifications for select
  using (user_id::text = auth.uid()::text or public.is_admin());

create policy "notifications_insert_own"
  on public.notifications for insert
  with check (user_id::text = auth.uid()::text);

create policy "notifications_update_own_or_admin"
  on public.notifications for update
  using (user_id::text = auth.uid()::text or public.is_admin())
  with check (user_id::text = auth.uid()::text or public.is_admin());

-- inbox_messages
create policy "inbox_read_participants_or_admin"
  on public.inbox_messages for select
  using (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or public.is_admin()
  );

create policy "inbox_insert_sender"
  on public.inbox_messages for insert
  with check (
    sender_id::text = auth.uid()::text
    and lower(sender_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

create policy "inbox_update_participants"
  on public.inbox_messages for update
  using (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or public.is_admin()
  )
  with check (
    sender_id::text = auth.uid()::text
    or recipient_id::text = auth.uid()::text
    or lower(recipient_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or public.is_admin()
  );

-- video_comments
create policy "video_comments_read_enrolled_or_owner"
  on public.video_comments for select
  using (
    exists (
      select 1
      from public.videos v
      join public."Courses" c on c.id = v.course_id
      where v.id = video_comments.video_id
        and (
          c.instructor_id::text = auth.uid()::text
          or public.is_admin()
        )
    )
    or exists (
      select 1
      from public.videos v
      join public.enrollments e on e.course_id::text = v.course_id::text
      where v.id = video_comments.video_id
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

create policy "video_comments_insert_enrolled"
  on public.video_comments for insert
  with check (
    user_id::text = auth.uid()::text
    and exists (
      select 1
      from public.videos v
      join public.enrollments e on e.course_id::text = v.course_id::text
      where v.id = video_comments.video_id
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

-- course_ratings
create policy "course_ratings_read_any"
  on public.course_ratings for select
  using (true);

create policy "course_ratings_insert_enrolled"
  on public.course_ratings for insert
  with check (
    user_id::text = auth.uid()::text
    and exists (
      select 1
      from public.enrollments e
      where e.course_id::text = course_ratings.course_id::text
        and coalesce(e.status, 'active') = 'active'
        and (
          e.user_id::text = auth.uid()::text
          or lower(e.user_id::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    )
  );

create policy "course_ratings_update_own"
  on public.course_ratings for update
  using (user_id::text = auth.uid()::text)
  with check (user_id::text = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- 8b. Public, URL-free lesson list for published courses. Lets prospective
--     buyers (and logged-out visitors) see the full curriculum — titles,
--     durations, which lessons are free — without exposing paid video URLs.
--     The view is owned by the migration role, so it bypasses videos RLS and
--     returns every lesson of a published course; the sensitive video_url
--     column is simply not selected.
-- ---------------------------------------------------------------------------
drop view if exists public.lesson_previews;
create view public.lesson_previews as
  select v.id, v.course_id, v.title, v.duration, v.order_index, v.is_free
  from public.videos v
  join public."Courses" c on c.id = v.course_id
  where c.is_published = true;
grant select on public.lesson_previews to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 9. Backfill: course/instructor display names from approved applications.
-- ---------------------------------------------------------------------------
update public.profiles p
set full_name = trim(a.name || ' ' || a.surname)
from public.teacher_applications a
where p.user_id = a.user_id
  and a.status = 'approved'
  and nullif(trim(a.name || ' ' || a.surname), '') is not null
  and (p.full_name is null or trim(p.full_name) = '');

update public."Courses" c
set instructor_name = p.full_name
from public.profiles p
where c.instructor_id = p.user_id
  and (c.instructor_name is null or trim(c.instructor_name) = '')
  and nullif(trim(p.full_name), '') is not null;

-- Backfill order_index on older lessons that have none, so the curriculum sorts
-- correctly and the first-lesson preview resolves. Uses insertion order (id).
update public.videos v
set order_index = ranked.rn
from (
  select id, row_number() over (partition by course_id order by id) as rn
  from public.videos
  where order_index is null or order_index = 0
) ranked
where v.id = ranked.id;

-- ---------------------------------------------------------------------------
-- 10. Normalize enrollments to email-keyed (issue #11). The admin grants access
--     by email, so email is the canonical key. Convert any legacy UUID-keyed
--     rows to the owner's lowercased email. First drop a UUID row when an email
--     row already exists for the same course (avoids a unique-constraint clash).
-- ---------------------------------------------------------------------------
delete from public.enrollments e
using auth.users u
where e.user_id = u.id::text
  and exists (
    select 1 from public.enrollments e2
    where e2.course_id = e.course_id
      and lower(e2.user_id) = lower(u.email)
  );

update public.enrollments e
set user_id = lower(u.email)
from auth.users u
where e.user_id = u.id::text
  and u.email is not null;

-- ---------------------------------------------------------------------------
-- 11. Single active session per user (concurrent-session limiting, Option A).
--     Each login writes a fresh session_token here, overwriting the previous
--     one ("invalidate old session on new login"). The app subscribes to this
--     row via Realtime and logs out a device whose stored token no longer
--     matches. One row per user (user_id is the primary key).
-- ---------------------------------------------------------------------------
create table if not exists public.user_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  session_token text not null,
  last_active timestamptz not null default now(),
  device_info text,
  updated_at timestamptz not null default now()
);

grant select, insert, update on public.user_sessions to authenticated;

alter table public.user_sessions enable row level security;

drop policy if exists "user_sessions_own" on public.user_sessions;
create policy "user_sessions_own"
  on public.user_sessions for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Stream changes to the owner so the previous device is kicked instantly.
do $$
begin
  alter publication supabase_realtime add table public.user_sessions;
exception
  when duplicate_object then null;
  when others then null;
end $$;

notify pgrst, 'reload schema';
