-- Minimal teacher application setup.
-- Run this first if the app says teacher_applications is missing from schema cache.

create table if not exists public.teacher_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  surname text not null,
  phone text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create unique index if not exists teacher_applications_one_pending_per_user
  on public.teacher_applications (user_id)
  where status = 'pending';

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.teacher_applications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.teacher_applications enable row level security;

drop policy if exists "teacher_applications_insert_own_pending" on public.teacher_applications;
drop policy if exists "teacher_applications_read_own_or_admin" on public.teacher_applications;
drop policy if exists "teacher_applications_admin_update" on public.teacher_applications;

create policy "teacher_applications_insert_own_pending"
  on public.teacher_applications for insert
  with check (
    user_id = auth.uid()
    and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status = 'pending'
  );

create policy "teacher_applications_read_own_or_admin"
  on public.teacher_applications for select
  using (
    user_id = auth.uid()
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "teacher_applications_admin_update"
  on public.teacher_applications for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create or replace function public.admin_review_teacher_application(application_id bigint, decision text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user uuid;
  target_full_name text;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'qafarzadep@gmail.com' then
    raise exception 'Yalnız admin müəllim müraciətlərini yoxlaya bilər';
  end if;

  if decision not in ('approved', 'rejected') then
    raise exception 'Qərar approved və ya rejected olmalıdır';
  end if;

  select user_id, trim(name || ' ' || surname) into target_user, target_full_name
  from public.teacher_applications
  where id = application_id
    and status = 'pending';

  if target_user is null then
    raise exception 'Təsdiq gözləyən müraciət tapılmadı';
  end if;

  update public.teacher_applications
  set status = decision,
      reviewed_at = now()
  where id = application_id;

  if decision = 'approved' then
    insert into public.profiles (user_id, full_name, role)
    values (target_user, target_full_name, 'instructor')
    on conflict (user_id) do update
      set role = 'instructor',
          full_name = excluded.full_name;
  end if;
end;
$$;

grant execute on function public.admin_review_teacher_application(bigint, text) to authenticated;

notify pgrst, 'reload schema';
