-- Teacher application flow for Bil-X.
-- Run this in Supabase SQL Editor.

create table if not exists public.teacher_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  surname text not null,
  phone text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create unique index if not exists teacher_applications_one_pending_per_user
  on public.teacher_applications (user_id)
  where status = 'pending';

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.teacher_applications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.teacher_applications enable row level security;
alter table public.profiles enable row level security;
alter table public."Courses" enable row level security;
alter table public.videos enable row level security;

drop policy if exists "profiles_read_own_or_admin" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
drop policy if exists "profiles_admin_update_all" on public.profiles;

create policy "profiles_read_own_or_admin"
  on public.profiles for select
  using (
    user_id = auth.uid()
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "profiles_insert_own"
  on public.profiles for insert
  with check (
    user_id = auth.uid()
    and role = 'student'
  );

create policy "profiles_admin_update_all"
  on public.profiles for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

drop policy if exists "teacher_applications_insert_own_pending" on public.teacher_applications;
drop policy if exists "teacher_applications_read_own_or_admin" on public.teacher_applications;
drop policy if exists "teacher_applications_admin_update" on public.teacher_applications;

create policy "teacher_applications_insert_own_pending"
  on public.teacher_applications for insert
  with check (
    user_id = auth.uid()
    and email = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status = 'pending'
  );

create policy "teacher_applications_read_own_or_admin"
  on public.teacher_applications for select
  using (
    user_id = auth.uid()
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com'
  );

create policy "teacher_applications_admin_update"
  on public.teacher_applications for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create or replace function public.admin_review_teacher_application(application_id bigint, decision text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user uuid;
  target_full_name text;
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'qafarzadep@gmail.com' then
    raise exception 'Only admin can review teacher applications';
  end if;

  if decision not in ('approved', 'rejected') then
    raise exception 'Decision must be approved or rejected';
  end if;

  select user_id, trim(name || ' ' || surname) into target_user, target_full_name
  from public.teacher_applications
  where id = application_id
    and status = 'pending';

  if target_user is null then
    raise exception 'Pending application not found';
  end if;

  update public.teacher_applications
  set status = decision,
      reviewed_at = now()
  where id = application_id;

  if decision = 'approved' then
    insert into public.profiles (user_id, full_name, role)
    values (target_user, target_full_name, 'instructor')
    on conflict (user_id) do update
      set role = 'instructor',
          full_name = excluded.full_name;
  end if;
end;
$$;

grant execute on function public.admin_review_teacher_application(bigint, text) to authenticated;

-- New users must start as students even if the frontend or metadata sends another role.
create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    'student'
  )
  on conflict (user_id) do update
    set full_name = coalesce(excluded.full_name, public.profiles.full_name);

  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;

create trigger create_profile_after_signup
  after insert on auth.users
  for each row execute function public.create_profile_for_new_user();

-- Courses and lesson management must require an approved instructor profile.
drop policy if exists "courses_public_read_approved" on public."Courses";
drop policy if exists "courses_instructor_read_own" on public."Courses";
drop policy if exists "courses_admin_read_all" on public."Courses";
drop policy if exists "courses_instructor_insert_own" on public."Courses";
drop policy if exists "courses_instructor_update_own" on public."Courses";
drop policy if exists "courses_admin_update_all" on public."Courses";

create policy "courses_public_read_approved"
  on public."Courses" for select
  using (is_published = true);

create policy "courses_instructor_read_own"
  on public."Courses" for select
  using (
    instructor_id = auth.uid()
    and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'instructor')
  );

create policy "courses_admin_read_all"
  on public."Courses" for select
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

create policy "courses_instructor_insert_own"
  on public."Courses" for insert
  with check (
    instructor_id = auth.uid()
    and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'instructor')
  );

create policy "courses_instructor_update_own"
  on public."Courses" for update
  using (
    instructor_id = auth.uid()
    and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'instructor')
  )
  with check (
    instructor_id = auth.uid()
    and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'instructor')
  );

create policy "courses_admin_update_all"
  on public."Courses" for update
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'qafarzadep@gmail.com');

drop policy if exists "videos_insert_for_course_owner" on public.videos;
drop policy if exists "videos_update_for_course_owner" on public.videos;
drop policy if exists "videos_delete_for_course_owner" on public.videos;

create policy "videos_insert_for_course_owner"
  on public.videos for insert
  with check (
    exists (
      select 1
      from public."Courses" c
      join public.profiles p on p.user_id = auth.uid() and p.role = 'instructor'
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

create policy "videos_update_for_course_owner"
  on public.videos for update
  using (
    exists (
      select 1
      from public."Courses" c
      join public.profiles p on p.user_id = auth.uid() and p.role = 'instructor'
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public."Courses" c
      join public.profiles p on p.user_id = auth.uid() and p.role = 'instructor'
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

create policy "videos_delete_for_course_owner"
  on public.videos for delete
  using (
    exists (
      select 1
      from public."Courses" c
      join public.profiles p on p.user_id = auth.uid() and p.role = 'instructor'
      where c.id = videos.course_id
        and c.instructor_id = auth.uid()
    )
  );

notify pgrst, 'reload schema';
